# Generated by Django 2.2.28 on 2022-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresswfiahypuxr'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresswfiahypuxr',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
